version: '3'
services:
  dripdrop-server:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-server
    expose:
      - 5000
    networks:
      - docker-net
      - dripdrop-net

  dripdrop-worker:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-worker
    deploy:
      replicas: 2
    networks:
      - dripdrop-net

  dripdrop-postgres:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-postgres
    networks:
      - dripdrop-net

  dripdrop-redis:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-redis
    networks:
      - dripdrop-net

volumes:
  postgres_volume: {}
  redis_volume: {}

networks:
  docker-net:
    external: true
  dripdrop-net: {}
