version: '2.4'
services:
  server:
    extends:
      file: docker-compose.base.yml
      service: server
    volumes:
      - type: bind
        source: ./
        target: /src
    ports:
      - 5000:5000/tcp

  worker:
    extends:
      file: docker-compose.base.yml
      service: worker
    volumes:
      - type: bind
        source: ./
        target: /src

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  pgadmin:
    extends:
      file: docker-compose.base.yml
      service: pgadmin
    ports:
      - 5050:80

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

volumes:
  postgres_volume: {}
  redis_volume: {}
  temp_volume: {}
