services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - prod
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: dripdrop
      POSTGRES_PASSWORD: dripdrop
      POSTGRES_DB: dripdrop
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis_volume
        target: /data

volumes:
  postgres_volume: {}
  redis_volume: {}
