version: '2.4'
services:
  server:
    extends:
      file: docker-compose.base.yml
      service: server
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /src

  worker:
    extends:
      file: docker-compose.base.yml
      service: worker
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /src

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  pgadmin:
    extends:
      file: docker-compose.base.yml
      service: pgadmin

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  selenium:
    extends:
      file: docker-compose.base.yml
      service: selenium

volumes:
  postgres_volume: {}
  redis_volume: {}
