x-depends-postgres: &depends_on_postgres
  depends_on:
    postgres:
      condition: service_healthy

x-depends-database: &depends_on_database
  <<: *depends_on_postgres
  depends_on:
    redis:
      condition: service_healthy

version: '2.4'
name: dripdrop-dev
services:
  server:
    extends: 
      file: docker-compose.base.yml
      service: server
    build:
      dockerfile: dockerfiles/Dockerfile.dev
    environment:
      ENV: development
    volumes:
      - type: bind
        source: ./
        target: /src
      - type: volume
        source: server_venv
        target: /src/.venv 
    <<: *depends_on_database

  worker:
    extends: 
      file: docker-compose.base.yml
      service: worker
    build:
      dockerfile: dockerfiles/Dockerfile.dev
    environment:
      ENV: development
    volumes:
      - type: bind
        source: ./
        target: /src
      - type: volume
        source: worker_venv
        target: /src/.venv 
    <<: *depends_on_database

  postgres:
    extends: 
      file: docker-compose.base.yml
      service: postgres

  pgadmin:
    extends: 
      file: docker-compose.base.yml
      service: pgadmin
    <<: *depends_on_postgres

  redis:
    extends: 
      file: docker-compose.base.yml
      service: redis

volumes:
  worker_venv: {}
  server_venv: {}
  postgresql: {}
  redis: {}
