version: '3'
services:
  dripdrop-server:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-server
    environment:
      VIRTUAL_HOST: dripdrop.icu,www.dripdrop.icu
      VIRTUAL_PATH: /api
      LETSENCRYPT_HOST: dripdrop.icu,www.dripdrop.icu
      VIRTUAL_PORT: 5000
    volumes:
      - type: volume
        source: nginx_vhost
        target: /nginx/vhost.d
    expose:
      - 5000
    networks:
      - docker_net
      - dripdrop-net

  dripdrop-worker:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-worker
    deploy:
      replicas: 2
    networks:
      - dripdrop-net

  dripdrop-postgres:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-postgres
    networks:
      - dripdrop-net

  dripdrop-pgadmin:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-pgadmin
    environment:
      VIRTUAL_HOST: db.dripdrop.icu
      LETSENCRYPT_HOST: db.dripdrop.icu
    networks:
      - docker_net
      - dripdrop-net

  dripdrop-redis:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-redis
    networks:
      - dripdrop-net

volumes:
  postgres_volume: {}
  redis_volume: {}
  nginx_vhost:
    external: true

networks:
  docker_net:
    external: true
  dripdrop-net:
