x-logging: &logging
  logging:
    driver: syslog
    options:
      syslog-address: $TELEGRAF_SYSLOG_ADDRESS:$TELEGRAF_SYSLOG_PORT
      syslog-format: rfc5424micro
      tag: '{{.Name}}'

x-depends-influxdb: &depends_on_influxdb
  depends_on:
    influxdb:
      condition: service_healthy

x-depends-telegraf: &depends_on_telegraf
  depends_on:
    telegraf: 
      condition: service_started

x-depends-database: &depends_on_database
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy

x-depends-all: &depends_on_all
  <<: 
    - *depends_on_telegraf
    - *depends_on_database

version: '2.4'
name: dripdrop-base
services:
  server:
    platform: linux/amd64
    container_name: server
    restart: always
    build:
      dockerfile: dockerfiles/Dockerfile.dev
    entrypoint: ./scripts/server.sh
    environment:
      SERVER_PORT: $SERVER_PORT
    ports:
      - $SERVER_PORT:$SERVER_PORT
    <<: 
      - *logging
      - *depends_on_all

  worker:
    platform: linux/amd64
    container_name: worker
    restart: always
    build:
      dockerfile: dockerfiles/Dockerfile.dev
    entrypoint: ./scripts/worker.sh
    <<: 
      - *logging
      - *depends_on_all

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - type: volume
        source: postgresql
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    <<: 
      - *logging
      - *depends_on_telegraf
    healthcheck:
      test: pg_isready -U $DATABASE
      interval: 10s
      start_period: 1s
      timeout: 1m30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $DATABASE_USER@$DATABASE.com
      PGADMIN_DEFAULT_PASSWORD: $DATABASE_PASSWORD
    ports:
      - 8000:8000
    <<: 
      - *logging
      - *depends_on_telegraf
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - type: volume
        source: redis
        target: /data
    ports:
      - 6379:6379
    <<: 
      - *logging
      - *depends_on_telegraf
    healthcheck:
      test: redis-cli ping
      interval: 10s
      start_period: 1s
      timeout: 1m30s

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: $INFLUXDB_USERNAME
      DOCKER_INFLUXDB_INIT_PASSWORD: $INFLUXDB_PASSWORD
      DOCKER_INFLUXDB_INIT_ORG: $INFLUXDB_ORG
      DOCKER_INFLUXDB_INIT_BUCKET: $INFLUXDB_BUCKET
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: $INFLUXDB_TOKEN
    volumes:
      - type: volume
        source: influxdb
        target: /var/lib/influxdb
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 10s
      start_period: 1s
      timeout: 1m30s

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    environment:
      HOST_MOUNT_PREFIX: /hostfs
      HOST_PROC: /hostfs/proc
      INFLUXDB_USERNAME: $INFLUXDB_USERNAME
      INFLUXDB_PASSWORD: $INFLUXDB_PASSWORD
      INFLUXDB_ORG: $INFLUXDB_ORG
      INFLUXDB_BUCKET: $INFLUXDB_BUCKET
      INFLUXDB_TOKEN: $INFLUXDB_TOKEN
      INFLUXDB_URL: $INFLUXDB_URL
      TELEGRAF_SYSLOG_ADDRESS: $TELEGRAF_SYSLOG_ADDRESS
      TELEGRAF_SYSLOG_PORT: $TELEGRAF_SYSLOG_PORT
    volumes:
      - type: bind
        source: ./config/telegraf.conf
        target: /etc/telegraf/telegraf.conf
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /proc
        target: /hostfs/proc
        read_only: true
    ports:
      - "6514:6514/udp"
    <<:
      - *depends_on_influxdb

  chronograf:
    image: chronograf
    container_name: chronograf
    restart: always
    environment:
      INFLUXDB_USERNAME: $INFLUXDB_USERNAME
      INFLUXDB_PASSWORD: $INFLUXDB_PASSWORD
      INFLUXDB_ORG: $INFLUXDB_ORG
      INFLUXDB_TOKEN: $INFLUXDB_TOKEN
      INFLUXDB_URL: $INFLUXDB_URL
    volumes:
      - type: volume
        source: chronograf
        target: /var/lib/chronograf
    ports:
      - 8888:8888
    <<: 
      - *depends_on_telegraf
      - *depends_on_influxdb
