version: '2.4'
name: dripdrop
services:
  server:
    platform: linux/amd64
    container_name: server
    restart: always
    volumes:
      - ./:/src
      - ./data/server/logs:/src/logs
    env_file: .env
    build:
      dockerfile: dockerfiles/Dockerfile.dev
    entrypoint: |
      bash -c "
        set -e
        source venv/bin/activate
        alembic upgrade head
        uvicorn dripdrop.app:app --reload --reload-dir dripdrop --host 0.0.0.0 --port $SERVER_PORT --log-config ./config/logging.yml
      "
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - $SERVER_PORT:$SERVER_PORT
  worker:
    platform: linux/amd64
    container_name: worker
    restart: always
    volumes:
      - ./:/src
      - ./data/worker/logs:/src/logs
    env_file: .env
    build:
      dockerfile: dockerfiles/Dockerfile.dev
    entrypoint: |
      bash -c "
        set -e
        source venv/bin/activate
        watchfiles 'python worker.py --logging' ./worker.py
      "
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    healthcheck:
      test: pg_isready
      interval: 10s
      start_period: 1s
      timeout: 1m30s
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE
      POSTGRES_HOST_AUTH_METHOD: md5
  redis:
    image: redis
    container_name: redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      start_period: 1s
      timeout: 1m30s
    volumes:
      - ./data/redis:/data
    env_file: '.env'
