version: '2.4'
name: dripdrop
services:
  web:
    platform: linux/amd64
    container_name: web
    restart: always
    volumes:
      - ./:/src
      - ./data/web/logs:/src/logs
    env_file: .env
    build:
      dockerfile: dockerfiles/Dockerfile.dev.web
    entrypoint: ./scripts/web.dev.sh
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - $SERVER_PORT:$SERVER_PORT
      - $PORT:$PORT
  worker:
    platform: linux/amd64
    container_name: worker
    restart: always
    volumes:
      - ./:/src
      - ./data/worker/logs:/src/logs
    env_file: .env
    build:
      dockerfile: dockerfiles/Dockerfile.dev.worker
    entrypoint: watchfiles 'python worker.py' ./worker.py
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      interval: 10s
      start_period: 1s
      timeout: 1m30s
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST_AUTH_METHOD: md5
  redis:
    image: redis
    container_name: redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      start_period: 1s
      timeout: 1m30s
    env_file: '.env'
