x-restart_policy: &restart_policy
  restart: unless-stopped

x-logging: &logging
  logging:
    driver: 'local'
    options:
      max-size: '10m'
      max-file: '5'

x-depends-database: &depends-database
  postgres:
    condition: service_healthy

x-depends-redis: &depends-redis
  redis:
    condition: service_healthy

x-depends-all: &depends-all
  depends_on:
    <<:
      - *depends-database
      - *depends-redis

version: '3'
services:
  server:
    image: dripdrop/image
    command: [ "./scripts/server.sh" ]
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5000/healthcheck"
        ]
      interval: 30s
    environment:
      ENV: ${ENV}
    <<:
      - *depends-all
      - *logging
      - *restart_policy

  worker:
    image: dripdrop/image
    command: [ "./scripts/worker.sh" ]
    environment:
      ENV: ${ENV}
      REDIS_URL: ${REDIS_URL}
    <<:
      - *depends-all
      - *logging
      - *restart_policy

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DATABASE}" ]
      interval: 10s
    <<:
      - *logging
      - *restart_policy

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_USER}@${DATABASE}.com
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-O",
          "-",
          "http://localhost/misc/ping"
        ]
      interval: 30s
    depends_on:
      <<: *depends-database
    <<:
      - *logging
      - *restart_policy

  redis:
    image: redis
    volumes:
      - type: volume
        source: redis_volume
        target: /data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
    <<:
      - *logging
      - *restart_policy
