version: '2.4'
services:
  server:
    extends:
      file: docker-compose.base.yml
      service: server
    environment:
      ENV: production

  worker:
    extends:
      file: docker-compose.base.yml
      service: worker
    environment:
      ENV: production
    deploy:
      replicas: 2

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  pgadmin:
    extends:
      file: docker-compose.base.yml
      service: pgadmin

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  influxdb:
    extends:
      file: docker-compose.base.yml
      service: influxdb

  telegraf:
    extends:
      file: docker-compose.base.yml
      service: telegraf

  grafana:
    extends:
      file: docker-compose.base.yml
      service: grafana

volumes:
  worker_venv: {}
  server_venv: {}
  postgres_volume: {}
  redis_volume: {}
  influxdb_volume: {}
