version: '2.4'
services:
  dripdrop-server:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-server
    volumes:
      - type: bind
        source: ./
        target: /src
    ports:
      - 5000:5000/tcp

  dripdrop-worker:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-worker
    volumes:
      - type: bind
        source: ./
        target: /src

  dripdrop-postgres:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-postgres
    ports:
      - 5432:5432

  dripdrop-redis:
    extends:
      file: docker-compose.base.yml
      service: dripdrop-redis

volumes:
  postgres_volume: {}
  redis_volume: {}
  temp_volume: {}
