version: '2.4'
services:
  server:
    extends:
      file: docker-compose.base.yml
      service: server
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    environment:
      ENV: production

  worker:
    extends:
      file: docker-compose.base.yml
      service: worker
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    environment:
      ENV: production
    deploy:
      replicas: 2

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  pgadmin:
    extends:
      file: docker-compose.base.yml
      service: pgadmin

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  influxdb:
    extends:
      file: docker-compose.base.yml
      service: influxdb

  telegraf:
    extends:
      file: docker-compose.base.yml
      service: telegraf

  grafana:
    extends:
      file: docker-compose.base.yml
      service: grafana

  selenium:
    extends:
      file: docker-compose.base.yml
      service: selenium

volumes:
  postgres_volume: {}
  redis_volume: {}
  influxdb_volume: {}
