[tool.poetry]
name = "dripdrop"
version = "0.1.0"
description = ""
authors = ["Mohamed Raffik"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
black = "^22.8.0"
alembic = "^1.8.1"
fastapi = {extras = ["all"], version = "^0.84.0"}
gunicorn = "^20.1.0"
croniter = "^1.3.7"
boto3 = "^1.24.73"
aioredis = "^2.0.1"
redis = "^4.3.4"
requests = "^2.28.1"
rq = "^1.11.0"
yt-dlp = "^2022.9.1"
mutagen = "^1.45.1"
pydub = "^0.25.1"
asgiref = "^3.5.2"
pydantic = {extras = ["email"], version = "^1.10.2"}
flake8 = "^5.0.4"
psycopg2-binary = "^2.9.3"
beautifulsoup4 = "^4.11.1"
watchfiles = "^0.17.0"
sqlalchemy = {extras = ["asyncio"], version = "^1.4.42"}
asyncpg = "^0.27.0"
pyjwt = {extras = ["crypto"], version = "^2.6.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pytest = "^7.2.0"
aiosqlite = "^0.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "noauth: marks tests to not use auto login",
    "nogoogleauth: marks tests to not auto create google account"
]
