version: 2

jobs:
  build and deploy:
    docker:
      - image: python
    steps:
      - run:
          name: Copy Server Deploy Script to VM
          command: scp -v ./scripts/web_deploy.sh $SSH_USER@$SSH_HOST:~
      - run:
          name: Deploy Over SSH
          command: ssh -o StrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST "chmod +x ./deploy.sh && ./deploy.sh"

workflows:
  version: 2
  deploy:
    jobs:
      - build and deploy:
          filters:
            branches:
              only: main # only deploy on the main branch
