"""empty message

Revision ID: 3834372a2d96
Revises: 9083dc87022c
Create Date: 2025-06-20 16:59:23.870380

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3834372a2d96"
down_revision = "9083dc87022c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "music_jobs",
        "completed",
        existing_type=sa.BOOLEAN(),
        type_=sa.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "music_jobs",
        "failed",
        existing_type=sa.BOOLEAN(),
        type_=sa.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "music_jobs",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "users",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "youtube_channels",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "youtube_new_subscriptions",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "youtube_subscriptions",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "youtube_user_channels",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "youtube_video_categories",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "youtube_video_likes",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "youtube_video_queues",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "youtube_video_watches",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "youtube_videos",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "youtube_videos",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "youtube_video_watches",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "youtube_video_queues",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "youtube_video_likes",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "youtube_video_categories",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "youtube_user_channels",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "youtube_subscriptions",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "youtube_new_subscriptions",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "youtube_channels",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "music_jobs",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "music_jobs",
        "failed",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "music_jobs",
        "completed",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.BOOLEAN(),
        nullable=False,
    )
    # ### end Alembic commands ###
