version: 1
disable_existing_loggers: True
formatters:
  generic:
    format: "[%(process)d] [%(name)s] [%(levelname)s] %(message)s"
    datefmt: "[%Y-%m-%d %H:%M:%S %z]"
    class: "logging.Formatter"
filters:
  info:
    (): "config.logging.Filter"
handlers:
  console:
    level: "INFO"
    formatter: "generic"
    filters: ["info"]
    class: "logging.StreamHandler"
    stream: "ext://sys.stdout"
  error_console:
    level: "WARNING"
    formatter: "generic"
    class: "logging.StreamHandler"
    stream: "ext://sys.stderr"
loggers:
  dripdrop:
    level: "INFO"
    handlers: ["console", "error_console"]
  uvicorn.error:
    level: "INFO"
    handlers: ["console", "error_console"]
  uvicorn.access:
    level: "INFO"
    handlers: ["console"]
  gunicorn.error:
    level: "INFO"
    handlers: ["console", "error_console"]
  gunicorn.access:
    level: "INFO"
    handlers: ["console"]
  rq.worker:
    level: "INFO"
    handlers: ["console", "error_console"]
  rq.queue:
    level: "INFO"
    handlers: ["console", "error_console"]
