version: 1
disable_existing_loggers: False
formatters:
  generic:
    format: "%(asctime)s [%(process)d] [%(name)s] [%(levelname)s] %(message)s"
    datefmt: "[%Y-%m-%d %H:%M:%S %z]"
    class: "logging.Formatter"
filters:
  info:
    (): "config.logging.ErrorFilter"
handlers:
  console:
    level: "INFO"
    formatter: "generic"
    filters: ["info"]
    class: "logging.StreamHandler"
    stream: "ext://sys.stdout"
  file:
    level: "INFO"
    formatter: "generic"
    filters: ["info"]
    class: "logging.handlers.RotatingFileHandler"
    filename: "./logs/log.log"
    maxBytes: 10000
    backupCount: 10
  error_console:
    level: "WARNING"
    formatter: "generic"
    class: "logging.StreamHandler"
    stream: "ext://sys.stderr"
  error_file:
    level: "WARNING"
    formatter: "generic"
    class: "logging.handlers.RotatingFileHandler"
    filename: "./logs/error.log"
    maxBytes: 100000000
    backupCount: 10
loggers:
  dripdrop:
    level: "INFO"
    handlers: ["console", "error_console", "file", "error_file"]
  uvicorn.error:
    level: "INFO"
    handlers: ["console", "error_console", "file", "error_file"]
  uvicorn.access:
    level: "INFO"
    handlers: ["console", "file"]
  gunicorn.error:
    level: "INFO"
    handlers: ["console", "error_console", "file", "error_file"]
  gunicorn.access:
    level: "INFO"
    handlers: ["console", "file"]
  rq.worker:
    level: "INFO"
    handlers: ["console", "error_console", "file", "error_file"]
