name: Server

on: [push, workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/server

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run linter
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Retrieve infiscal secrets
        uses: infisical/secrets-action@v1.0.12
        with:
          method: "universal"
          client-id: ${{ secrets.INFISCAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISCAL_CLIENT_SECRET }}
          project-slug: "dripdrop-1-hbh"
          env-slug: "dev"
          export-type: "file"
      - name: Add default values to .env file
        run: |
          printf "\n" >> .env
          echo "ASYNC_DATABASE_URL=postgresql+asyncpg://dripdrop:dripdrop@postgres/dripdrop" >> .env
          echo "REDIS_URL=redis://redis:6379" >> .env
          echo "TEST_ASYNC_DATABASE_URL=postgresql+asyncpg://dripdrop:dripdrop@postgres/dripdrop" >> .env
          echo "TEST_REDIS_URL=redis://redis:6379" >> .env
      - name: Run tests
        run: docker compose --profile prod --env-file .env run --rm server test
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
  deploy:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYYMMDD'}},enable={{is_default_branch}}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
