name: Server

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Export environment
        run: |
          echo ${{ secrets.ENV }} >> .env
      - name: Run tests
        run: |
          python docker.py --env production --action test
