name: Server

on: [push, workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/server

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run linter
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Create .env file from secrets
        run: |
          printf "ASYNC_DATABASE_URL=%q\n" "postgresql+asyncpg://dripdrop:dripdrop@postgres/dripdrop" >> .env
          printf "AWS_ACCESS_KEY_ID=%q\n" "${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          printf "AWS_ENDPOINT_URL=%q\n" "${{ secrets.AWS_ENDPOINT_URL }}" >> .env
          printf "AWS_REGION_NAME=%q\n" "${{ secrets.AWS_REGION_NAME }}" >> .env
          printf "AWS_SECRET_ACCESS_KEY=%q\n" "${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          printf "AWS_S3_ARTWORK_FOLDER=%q\n" "${{ secrets.AWS_S3_ARTWORK_FOLDER }}" >> .env
          printf "AWS_S3_BUCKET=%q\n" "${{ secrets.AWS_S3_BUCKET }}" >> .env
          printf "AWS_S3_MUSIC_FOLDER=%q\n" "${{ secrets.AWS_S3_MUSIC_FOLDER }}" >> .env
          printf "FERNET_KEY=%q\n" "${{ secrets.FERNET_KEY }}" >> .env
          printf "GOOGLE_API_KEY=%q\n" "${{ secrets.GOOGLE_API_KEY }}" >> .env
          printf "INVIDIOUS_API_URL=%q\n" "${{ secrets.INVIDIOUS_API_URL }}" >> .env
          printf "REDIS_URL=%q\n" "redis://redis:6379" >> .env
          printf "SECRET_KEY=%q\n" "${{ secrets.SECRET_KEY }}" >> .env
          printf "SENDGRID_API_KEY=%q\n" "${{ secrets.SENDGRID_API_KEY }}" >> .env
          printf "SMTP2GO_API_KEY=%q\n" "${{ secrets.SMTP2GO_API_KEY }}" >> .env
          printf "TEST_AWS_S3_BUCKET=%q\n" "${{ secrets.TEST_AWS_S3_BUCKET }}" >> .env
          printf "TEST_ASYNC_DATABASE_URL=%q\n" "postgresql+asyncpg://dripdrop:dripdrop@postgres/dripdrop" >> .env
          printf "TEST_REDIS_URL=%q\n" "redis://redis:6379" >> .env
          printf "TEST_WEBDAV_URL=%q\n" "${{ secrets.TEST_WEBDAV_URL }}" >> .env
          printf "TEST_WEBDAV_USERNAME=%q\n" "${{ secrets.TEST_WEBDAV_USERNAME }}" >> .env
          printf "TEST_WEBDAV_PASSWORD=%q\n" "${{ secrets.TEST_WEBDAV_PASSWORD }}" >> .env
      - name: Run tests
        run: docker compose --profile prod --env-file .env run --rm server test
  deploy:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYYMMDD'}},enable={{is_default_branch}}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
