name: Server

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: python:3.10
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: docker compose -f docker-compose.prod.yml run server bash -c "source venv/bin/activate && ENV=testing pytest"
