name: Server

on: [push, pull_request, workflow_dispatch]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Export environment
              run: |
                  echo "${{ secrets.ENV }}" >> .env
            - name: Run tests
              run: |
                  sudo python3 docker.py --env production --action test
    deploy:
        if: ${{ github.ref_name == 'main' }}
        runs-on: ubuntu-latest
        needs: test
        # permissions:
        #   contents: read
        #   packages: write
        #   attestations: write
        #   id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: dripdrop/server:latest
